<a href="https://colab.research.google.com/github/Gopikuppala7/MachineLearning/blob/main/bevarges_Prediction_Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Beverage.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol    quality  
0         8.8     Normal  
1         9.5     Normal  
2        10.1     Normal  
3         9.9     Normal  
4         9.9     Normal  
...       ...        ...  
4893     11.2     Normal  
4894      9.6     Normal  
4895      9.4     Normal  
4896     12.8  Excellent  
4897     11.8     Normal  

[4898 rows x 12 columns]

In [ ]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
df.duplicated().sum()

937

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         4898 non-null   float64
 1   volatile acidity      4898 non-null   float64
 2   citric acid           4898 non-null   float64
 3   residual sugar        4898 non-null   float64
 4   chlorides             4898 non-null   float64
 5   free sulfur dioxide   4898 non-null   float64
 6   total sulfur dioxide  4898 non-null   float64
 7   density               4898 non-null   float64
 8   pH                    4898 non-null   float64
 9   sulphates             4898 non-null   float64
 10  alcohol               4898 non-null   float64
 11  quality               4898 non-null   object 
dtypes: float64(11), object(1)
memory usage: 459.3+ KB


In [ ]:
df['volatile acidity'].value_counts()

0.280    263
0.240    253
0.260    240
0.250    231
0.220    229
        ... 
0.545      1
0.135      1
0.905      1
0.685      1
0.355      1
Name: volatile acidity, Length: 125, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['volatile acidity'] = le.fit_transform(df['volatile acidity'])

df['volatile acidity'].value_counts()

38     263
30     253
34     240
32     231
26     229
      ... 
86       1
10       1
119      1
106      1
53       1
Name: volatile acidity, Length: 125, dtype: int64

In [ ]:
df['citric acid'].value_counts()

0.30    307
0.28    282
0.32    257
0.34    225
0.29    223
       ... 
1.66      1
1.23      1
0.86      1
0.11      1
0.99      1
Name: citric acid, Length: 87, dtype: int64

In [ ]:
df['citric acid'] = le.fit_transform(df['citric acid'])

In [ ]:
df['citric acid'].value_counts()

30    307
28    282
32    257
34    225
29    223
     ... 
86      1
85      1
80      1
11      1
83      1
Name: citric acid, Length: 87, dtype: int64

In [ ]:
ls = ['fixed acidity','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol','quality']
for col in ls:
  df[col] = le.fit_transform(df[col])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4898 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         4898 non-null   int64
 1   volatile acidity      4898 non-null   int64
 2   citric acid           4898 non-null   int64
 3   residual sugar        4898 non-null   int64
 4   chlorides             4898 non-null   int64
 5   free sulfur dioxide   4898 non-null   int64
 6   total sulfur dioxide  4898 non-null   int64
 7   density               4898 non-null   int64
 8   pH                    4898 non-null   int64
 9   sulphates             4898 non-null   int64
 10  alcohol               4898 non-null   int64
 11  quality               4898 non-null   int64
dtypes: int64(12)
memory usage: 459.3 KB


In [ ]:
X = df.drop(columns='volatile acidity')
y = df['volatile acidity']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
print(X.shape)
print(y.shape)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(4898, 11)
(4898,)
(3918, 11)
(3918,)
(980, 11)
(980,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

def LR(X_train, X_test, y_train, y_test):
  LogReg = LogisticRegression()

  LogReg.fit(X_train, y_train)
  y_pred = LogReg.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [ ]:
LR(X_train, X_test, y_train, y_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         6
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         9
          11       0.00      0.00      0.00        10
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00        15
          15       0.09      0.04      0.05        28
          17       0.08      0.06      0.07        32
          19       0.03      0.05      0.04        38
          21       0.05      0.03      0.04        33
          22   

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with n

In [ ]:
cor = df.corr()

In [ ]:
cor_1 = cor[abs(cor['volatile acidity'])>10]

In [ ]:
cor_1

fixed acidity  volatile acidity  citric acid  \
volatile acidity          -0.029201          1.000000    -0.154336   
citric acid                0.295541         -0.154336     1.000000   
residual sugar             0.097066          0.056392     0.093392   
chlorides                  0.035946          0.060936     0.114855   
free sulfur dioxide       -0.041819         -0.097969     0.108012   
total sulfur dioxide       0.097681          0.093860     0.123412   
alcohol                   -0.125895          0.080177    -0.068505   
quality                    0.096587          0.127823     0.011827   

                      residual sugar  chlorides  free sulfur dioxide  \
volatile acidity            0.056392   0.060936            -0.097969   
citric acid                 0.093392   0.114855             0.108012   
residual sugar              1.000000   0.114550             0.328173   
chlorides                   0.114550   1.000000             0.118689   
free sulfur dioxide         0.328173   0.118689             1.000000   
total sulfur dioxide        0.415415   0.231331             0.614679   
alcohol                    -0.431231  -0.414109            -0.257820   
quality                     0.077474   0.200625            -0.021929   

                      total sulfur dioxide   density        pH  sulphates  \
volatile acidity                  0.093860  0.006937 -0.035369  -0.038020   
citric acid                       0.123412  0.145641 -0.166968   0.065132   
residual sugar                    0.415415  0.814041 -0.198783  -0.029025   
chlorides                         0.231331  0.320022 -0.088845   0.021918   
free sulfur dioxide               0.614679  0.324300 -0.010235   0.056843   
total sulfur dioxide              1.000000  0.551888 -0.001026   0.133827   
alcohol                          -0.446216 -0.805503  0.104467  -0.029771   
quality                           0.127580  0.274971 -0.084518  -0.050673   

                       alcohol   quality  
volatile acidity      0.080177  0.127823  
citric acid          -0.068505  0.011827  
residual sugar       -0.431231  0.077474  
chlorides            -0.414109  0.200625  
free sulfur dioxide  -0.257820 -0.021929  
total sulfur dioxide -0.446216  0.127580  
alcohol               1.000000 -0.367149  
quality              -0.367149  1.000000

In [ ]:
cor_2 = cor[abs(cor['volatile acidity'])>0.1]

In [ ]:
lsFeat_1 = list(cor_1['volatile acidity'].index)

In [ ]:
lsFeat_2 = list(cor_2['volatile acidity'].index)

In [ ]:
df_1 = df[lsFeat_1]
df_2 = df[lsFeat_2]

In [ ]:
df_1

volatile acidity  citric acid  residual sugar  chlorides  \
0                   36           36             302         34   
1                   42           34              17         38   
2                   38           40             101         39   
3                   28           32             128         47   
4                   28           32             128         47   
...                ...          ...             ...        ...   
4893                24           29              17         28   
4894                46           36             120         36   
4895                30           19               9         30   
4896                40           30               7         11   
4897                24           38               2          9   

      free sulfur dioxide  total sulfur dioxide  alcohol  quality  
0                      57                   146        5        1  
1                      13                   106       12        1  
2                      33                    69       24        1  
3                      59                   163       21        1  
4                      59                   163       21        1  
...                   ...                   ...      ...      ...  
4893                   26                    64       47        1  
4894                   73                   144       15        1  
4895                   33                    83       11        1  
4896                   21                    82       84        0  
4897                   23                    70       65        1  

[4898 rows x 8 columns]

In [ ]:
df_2

volatile acidity  citric acid  quality
0                   36           36        1
1                   42           34        1
2                   38           40        1
3                   28           32        1
4                   28           32        1
...                ...          ...      ...
4893                24           29        1
4894                46           36        1
4895                30           19        1
4896                40           30        0
4897                24           38        1

[4898 rows x 3 columns]

In [ ]:
X1 = df_1.drop(columns='volatile acidity')
y1 = df['volatile acidity']

X2 = df_2.drop(columns='volatile acidity')
y2 = df['volatile acidity']

In [ ]:
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X1, y1, test_size = 0.2)

X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X2, y2, test_size = 0.2)

In [ ]:
print(X1.shape)
print(y1.shape)
print(X_train_1.shape)
print(y_train_1.shape)
print(X_test_1.shape)
print(y_test_1.shape)

(4898, 7)
(4898,)
(3918, 7)
(3918,)
(980, 7)
(980,)


In [ ]:
print(X2.shape)
print(y2.shape)
print(X_train_2.shape)
print(y_train_2.shape)
print(X_test_2.shape)
print(y_test_2.shape)

(4898, 2)
(4898,)
(3918, 2)
(3918,)
(980, 2)
(980,)


In [ ]:
LR(X_train_1, X_test_1, y_train_1, y_test_1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         7
           9       0.00      0.00      0.00         6
          11       0.10      0.10      0.10        10
          13       0.00      0.00      0.00        12
          15       0.00      0.00      0.00        36
          16       0.00      0.00      0.00         1
          17       0.00      0.00      0.00        28
          19       0.00      0.00      0.00        31
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00        30
          22       0.09      0.12      0.10        40
          24   

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with n

In [ ]:
LR(X_train_2, X_test_2, y_train_2, y_test_2)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         5
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00        10
          11       0.00      0.00      0.00        16
          12       0.00      0.00      0.00         2
          13       0.00      0.00      0.00        12
          14       0.00      0.00      0.00         1
          15       0.00      0.00      0.00        33
          16       0.00      0.00      0.00         1
          17       0.00      0.00      0.00        25
          19       0.04      0.29      0.07        28
          20   

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit