<a href="https://colab.research.google.com/github/Gopikuppala7/MachineLearning/blob/main/bevarages_Prediction_Logistic_Regression_GNB_Feature_Scaled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/Beverage.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol    quality  
0         8.8     Normal  
1         9.5     Normal  
2        10.1     Normal  
3         9.9     Normal  
4         9.9     Normal  
...       ...        ...  
4893     11.2     Normal  
4894      9.6     Normal  
4895      9.4     Normal  
4896     12.8  Excellent  
4897     11.8     Normal  

[4898 rows x 12 columns]

In [ ]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
df.duplicated().sum()

937

In [ ]:
 df = df.drop_duplicates()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3961 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         3961 non-null   float64
 1   volatile acidity      3961 non-null   float64
 2   citric acid           3961 non-null   float64
 3   residual sugar        3961 non-null   float64
 4   chlorides             3961 non-null   float64
 5   free sulfur dioxide   3961 non-null   float64
 6   total sulfur dioxide  3961 non-null   float64
 7   density               3961 non-null   float64
 8   pH                    3961 non-null   float64
 9   sulphates             3961 non-null   float64
 10  alcohol               3961 non-null   float64
 11  quality               3961 non-null   object 
dtypes: float64(11), object(1)
memory usage: 402.3+ KB


In [ ]:
df['quality'].value_counts()

Normal       2963
Excellent     825
Poor          173
Name: quality, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['quality'] = le.fit_transform(df['quality'])
df['quality'].value_counts()

1    2963
0     825
2     173
Name: quality, dtype: int64

In [ ]:
df['quality'].value_counts()

1    2963
0     825
2     173
Name: quality, dtype: int64

In [ ]:
df['quality'] = le.fit_transform(df['quality'])
df['quality'].value_counts()

1    2963
0     825
2     173
Name: quality, dtype: int64

In [ ]:
ls = ['quality']

for col in ls:
  df[col] = le.fit_transform(df[col])

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3961 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         3961 non-null   float64
 1   volatile acidity      3961 non-null   float64
 2   citric acid           3961 non-null   float64
 3   residual sugar        3961 non-null   float64
 4   chlorides             3961 non-null   float64
 5   free sulfur dioxide   3961 non-null   float64
 6   total sulfur dioxide  3961 non-null   float64
 7   density               3961 non-null   float64
 8   pH                    3961 non-null   float64
 9   sulphates             3961 non-null   float64
 10  alcohol               3961 non-null   float64
 11  quality               3961 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 402.3 KB


In [ ]:
X = df.drop(columns='quality')
y = df['quality']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

def LR(X_train, X_test, y_train, y_test):
  LogReg = LogisticRegression()
  LogReg.fit(X_train, y_train)

  y_pred = LogReg.predict(X_test)
  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [ ]:
LR(X_train, X_test, y_train, y_test)

[[ 34 141   0]
 [ 22 560   1]
 [  3  31   1]]
              precision    recall  f1-score   support

           0       0.58      0.19      0.29       175
           1       0.77      0.96      0.85       583
           2       0.50      0.03      0.05        35

    accuracy                           0.75       793
   macro avg       0.61      0.39      0.40       793
weighted avg       0.71      0.75      0.69       793



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
df.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.019214     0.298959   
volatile acidity          -0.019214          1.000000    -0.163228   
citric acid                0.298959         -0.163228     1.000000   
residual sugar             0.083620          0.098340     0.106269   
chlorides                  0.024036          0.086287     0.132590   
free sulfur dioxide       -0.058396         -0.102471     0.091681   
total sulfur dioxide       0.082425          0.102315     0.122845   
density                    0.266091          0.060603     0.160076   
pH                        -0.431274         -0.046954    -0.183015   
sulphates                 -0.017453         -0.021150     0.049442   
alcohol                   -0.110788          0.046815    -0.076514   
quality                    0.112778          0.134616     0.000151   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.083620   0.024036            -0.058396   
volatile acidity            0.098340   0.086287            -0.102471   
citric acid                 0.106269   0.132590             0.091681   
residual sugar              1.000000   0.076091             0.306835   
chlorides                   0.076091   1.000000             0.101272   
free sulfur dioxide         0.306835   0.101272             1.000000   
total sulfur dioxide        0.409583   0.191145             0.619437   
density                     0.820498   0.253088             0.294638   
pH                         -0.165997  -0.090573            -0.007750   
sulphates                  -0.020503   0.017871             0.037932   
alcohol                    -0.398167  -0.356928            -0.251768   
quality                     0.095588   0.180858            -0.024868   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                     0.082425  0.266091 -0.431274  -0.017453   
volatile acidity                  0.102315  0.060603 -0.046954  -0.021150   
citric acid                       0.122845  0.160076 -0.183015   0.049442   
residual sugar                    0.409583  0.820498 -0.165997  -0.020503   
chlorides                         0.191145  0.253088 -0.090573   0.017871   
free sulfur dioxide               0.619437  0.294638 -0.007750   0.037932   
total sulfur dioxide              1.000000  0.536868  0.008239   0.136544   
density                           0.536868  1.000000 -0.063734   0.082048   
pH                                0.008239 -0.063734  1.000000   0.142353   
sulphates                         0.136544  0.082048  0.142353   1.000000   
alcohol                          -0.446643 -0.760162  0.093095  -0.022850   
quality                           0.138183  0.285255 -0.106079  -0.048410   

                       alcohol   quality  
fixed acidity        -0.110788  0.112778  
volatile acidity      0.046815  0.134616  
citric acid          -0.076514  0.000151  
residual sugar       -0.398167  0.095588  
chlorides            -0.356928  0.180858  
free sulfur dioxide  -0.251768 -0.024868  
total sulfur dioxide -0.446643  0.138183  
density              -0.760162  0.285255  
pH                    0.093095 -0.106079  
sulphates            -0.022850 -0.048410  
alcohol               1.000000 -0.385087  
quality              -0.385087  1.000000

In [ ]:
cor = df.corr()

cor['quality']

fixed acidity           0.112778
volatile acidity        0.134616
citric acid             0.000151
residual sugar          0.095588
chlorides               0.180858
free sulfur dioxide    -0.024868
total sulfur dioxide    0.138183
density                 0.285255
pH                     -0.106079
sulphates              -0.048410
alcohol                -0.385087
quality                 1.000000
Name: quality, dtype: float64

In [ ]:
cor_1 = cor[abs(cor['quality'])>0.05]

cor_2 = cor[abs(cor['quality'])>0.1]

In [ ]:
cor_1

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.019214     0.298959   
volatile acidity          -0.019214          1.000000    -0.163228   
residual sugar             0.083620          0.098340     0.106269   
chlorides                  0.024036          0.086287     0.132590   
total sulfur dioxide       0.082425          0.102315     0.122845   
density                    0.266091          0.060603     0.160076   
pH                        -0.431274         -0.046954    -0.183015   
alcohol                   -0.110788          0.046815    -0.076514   
quality                    0.112778          0.134616     0.000151   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.083620   0.024036            -0.058396   
volatile acidity            0.098340   0.086287            -0.102471   
residual sugar              1.000000   0.076091             0.306835   
chlorides                   0.076091   1.000000             0.101272   
total sulfur dioxide        0.409583   0.191145             0.619437   
density                     0.820498   0.253088             0.294638   
pH                         -0.165997  -0.090573            -0.007750   
alcohol                    -0.398167  -0.356928            -0.251768   
quality                     0.095588   0.180858            -0.024868   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                     0.082425  0.266091 -0.431274  -0.017453   
volatile acidity                  0.102315  0.060603 -0.046954  -0.021150   
residual sugar                    0.409583  0.820498 -0.165997  -0.020503   
chlorides                         0.191145  0.253088 -0.090573   0.017871   
total sulfur dioxide              1.000000  0.536868  0.008239   0.136544   
density                           0.536868  1.000000 -0.063734   0.082048   
pH                                0.008239 -0.063734  1.000000   0.142353   
alcohol                          -0.446643 -0.760162  0.093095  -0.022850   
quality                           0.138183  0.285255 -0.106079  -0.048410   

                       alcohol   quality  
fixed acidity        -0.110788  0.112778  
volatile acidity      0.046815  0.134616  
residual sugar       -0.398167  0.095588  
chlorides            -0.356928  0.180858  
total sulfur dioxide -0.446643  0.138183  
density              -0.760162  0.285255  
pH                    0.093095 -0.106079  
alcohol               1.000000 -0.385087  
quality              -0.385087  1.000000

In [ ]:
cor_2

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.019214     0.298959   
volatile acidity          -0.019214          1.000000    -0.163228   
chlorides                  0.024036          0.086287     0.132590   
total sulfur dioxide       0.082425          0.102315     0.122845   
density                    0.266091          0.060603     0.160076   
pH                        -0.431274         -0.046954    -0.183015   
alcohol                   -0.110788          0.046815    -0.076514   
quality                    0.112778          0.134616     0.000151   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.083620   0.024036            -0.058396   
volatile acidity            0.098340   0.086287            -0.102471   
chlorides                   0.076091   1.000000             0.101272   
total sulfur dioxide        0.409583   0.191145             0.619437   
density                     0.820498   0.253088             0.294638   
pH                         -0.165997  -0.090573            -0.007750   
alcohol                    -0.398167  -0.356928            -0.251768   
quality                     0.095588   0.180858            -0.024868   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                     0.082425  0.266091 -0.431274  -0.017453   
volatile acidity                  0.102315  0.060603 -0.046954  -0.021150   
chlorides                         0.191145  0.253088 -0.090573   0.017871   
total sulfur dioxide              1.000000  0.536868  0.008239   0.136544   
density                           0.536868  1.000000 -0.063734   0.082048   
pH                                0.008239 -0.063734  1.000000   0.142353   
alcohol                          -0.446643 -0.760162  0.093095  -0.022850   
quality                           0.138183  0.285255 -0.106079  -0.048410   

                       alcohol   quality  
fixed acidity        -0.110788  0.112778  
volatile acidity      0.046815  0.134616  
chlorides            -0.356928  0.180858  
total sulfur dioxide -0.446643  0.138183  
density              -0.760162  0.285255  
pH                    0.093095 -0.106079  
alcohol               1.000000 -0.385087  
quality              -0.385087  1.000000

In [ ]:
ls_Feat1 = list(cor_1['quality'].index)

ls_Feat2 = list(cor_2['quality'].index)

print(ls_Feat1)
print(ls_Feat2)

print(len(ls_Feat1))
print(len(ls_Feat2))

['fixed acidity', 'volatile acidity', 'residual sugar', 'chlorides', 'total sulfur dioxide', 'density', 'pH', 'alcohol', 'quality']
['fixed acidity', 'volatile acidity', 'chlorides', 'total sulfur dioxide', 'density', 'pH', 'alcohol', 'quality']
9
8


In [ ]:
df_1 = df[ls_Feat1]

df_2 = df[ls_Feat2]

print(df.shape)
print(df_1.shape)
print(df_2.shape)

(3961, 12)
(3961, 9)
(3961, 8)


In [ ]:
X1 = df_1.drop(columns='quality')
y1 = df_1['quality']

X2 = df_2.drop(columns='quality')
y2 = df_2['quality']

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 0.2, random_state = 42)

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size = 0.2, random_state = 42)

In [ ]:
LR(X_train1, X_test1, y_train1, y_test1)

[[ 26 149   0]
 [ 19 563   1]
 [  2  32   1]]
              precision    recall  f1-score   support

           0       0.55      0.15      0.23       175
           1       0.76      0.97      0.85       583
           2       0.50      0.03      0.05        35

    accuracy                           0.74       793
   macro avg       0.60      0.38      0.38       793
weighted avg       0.70      0.74      0.68       793



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
LR(X_train2, X_test2, y_train2, y_test2)

[[ 18  58   0]
 [  8 295   0]
 [  2  16   0]]
              precision    recall  f1-score   support

           0       0.64      0.24      0.35        76
           1       0.80      0.97      0.88       303
           2       0.00      0.00      0.00        18

    accuracy                           0.79       397
   macro avg       0.48      0.40      0.41       397
weighted avg       0.73      0.79      0.74       397



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels wit

In [ ]:
from sklearn.naive_bayes import GaussianNB

def GNB(X_train, X_test, y_train, y_test):
  Gaussian = GaussianNB()
  Gaussian.fit(X_train, y_train)

  y_pred = Gaussian.predict(X_test)
  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [ ]:
GNB(X_train, X_test, y_train, y_test)

[[128  46   1]
 [147 401  35]
 [  6  19  10]]
              precision    recall  f1-score   support

           0       0.46      0.73      0.56       175
           1       0.86      0.69      0.76       583
           2       0.22      0.29      0.25        35

    accuracy                           0.68       793
   macro avg       0.51      0.57      0.52       793
weighted avg       0.74      0.68      0.70       793



In [ ]:
GNB(X_train1, X_test1, y_train1, y_test1)

[[128  47   0]
 [139 414  30]
 [  6  22   7]]
              precision    recall  f1-score   support

           0       0.47      0.73      0.57       175
           1       0.86      0.71      0.78       583
           2       0.19      0.20      0.19        35

    accuracy                           0.69       793
   macro avg       0.51      0.55      0.51       793
weighted avg       0.74      0.69      0.71       793



In [ ]:
GNB(X_train2, X_test2, y_train2, y_test2)

[[116  59   0]
 [119 438  26]
 [  5  23   7]]
              precision    recall  f1-score   support

           0       0.48      0.66      0.56       175
           1       0.84      0.75      0.79       583
           2       0.21      0.20      0.21        35

    accuracy                           0.71       793
   macro avg       0.51      0.54      0.52       793
weighted avg       0.74      0.71      0.72       793



In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

std = StandardScaler()
X_scl = std.fit_transform(X)

mm = MinMaxScaler()
X_mm = mm.fit_transform(X)

In [ ]:
X_train_scl, X_test_scl, y_train_scl, y_test_scl = train_test_split(X_scl, y, test_size = 0.2, random_state = 42)
X_train_mm, X_test_mm, y_train_mm, y_test_mm = train_test_split(X_mm, y, test_size = 0.2, random_state = 42)

In [ ]:
LR(X_train_scl, X_test_scl, y_train_scl, y_test_scl)

[[ 52 123   0]
 [ 28 552   3]
 [  1  34   0]]
              precision    recall  f1-score   support

           0       0.64      0.30      0.41       175
           1       0.78      0.95      0.85       583
           2       0.00      0.00      0.00        35

    accuracy                           0.76       793
   macro avg       0.47      0.41      0.42       793
weighted avg       0.71      0.76      0.72       793



In [ ]:
LR(X_train_mm, X_test_mm, y_train_mm, y_test_mm)

[[ 43 132   0]
 [ 27 555   1]
 [  2  33   0]]
              precision    recall  f1-score   support

           0       0.60      0.25      0.35       175
           1       0.77      0.95      0.85       583
           2       0.00      0.00      0.00        35

    accuracy                           0.75       793
   macro avg       0.46      0.40      0.40       793
weighted avg       0.70      0.75      0.70       793



In [ ]:
GNB(X_train_scl, X_test_scl, y_train_scl, y_test_scl)

[[131  43   1]
 [147 401  35]
 [  6  19  10]]
              precision    recall  f1-score   support

           0       0.46      0.75      0.57       175
           1       0.87      0.69      0.77       583
           2       0.22      0.29      0.25        35

    accuracy                           0.68       793
   macro avg       0.51      0.57      0.53       793
weighted avg       0.75      0.68      0.70       793



In [ ]:
GNB(X_train_mm, X_test_mm, y_train_mm, y_test_mm)

[[131  43   1]
 [147 401  35]
 [  6  19  10]]
              precision    recall  f1-score   support

           0       0.46      0.75      0.57       175
           1       0.87      0.69      0.77       583
           2       0.22      0.29      0.25        35

    accuracy                           0.68       793
   macro avg       0.51      0.57      0.53       793
weighted avg       0.75      0.68      0.70       793

