<a href="https://colab.research.google.com/github/Gopikuppala7/MachineLearning/blob/main/CREDITCARD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/creditcard.csv')
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [ ]:
df.duplicated().sum()

1081

In [ ]:
df.drop_duplicates()

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[283726 rows x 31 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [ ]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Class'] = le.fit_transform(df['Class'])

df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
ls = ['Class']

for col in ls:
  df[col] = le.fit_transform(df[col])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

x=independent variable
y=dependent variable

In [ ]:
X = df.drop(columns='Class')
y = df['Class']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

def LR(X_train, X_test, y_train, y_test):
  LogReg = LogisticRegression()
  LogReg.fit(X_train, y_train)

  y_pred = LogReg.predict(X_test)
  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [ ]:
LR(X_train, X_test, y_train, y_test)

[[56836    28]
 [   30    68]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.71      0.69      0.70        98

    accuracy                           1.00     56962
   macro avg       0.85      0.85      0.85     56962
weighted avg       1.00      1.00      1.00     56962



/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
df.corr()

Time            V1            V2            V3            V4  \
Time    1.000000  1.173963e-01 -1.059333e-02 -4.196182e-01 -1.052602e-01   
V1      0.117396  1.000000e+00  4.135835e-16 -1.227819e-15 -9.215150e-16   
V2     -0.010593  4.135835e-16  1.000000e+00  3.243764e-16 -1.121065e-15   
V3     -0.419618 -1.227819e-15  3.243764e-16  1.000000e+00  4.711293e-16   
V4     -0.105260 -9.215150e-16 -1.121065e-15  4.711293e-16  1.000000e+00   
V5      0.173072  1.812612e-17  5.157519e-16 -6.539009e-17 -1.719944e-15   
V6     -0.063016 -6.506567e-16  2.787346e-16  1.627627e-15 -7.491959e-16   
V7      0.084714 -1.005191e-15  2.055934e-16  4.895305e-16 -4.104503e-16   
V8     -0.036949 -2.433822e-16 -5.377041e-17 -1.268779e-15  5.697192e-16   
V9     -0.008660 -1.513678e-16  1.978488e-17  5.568367e-16  6.923247e-16   
V10     0.030617  7.388135e-17 -3.991394e-16  1.156587e-15  2.232685e-16   
V11    -0.247689  2.125498e-16  1.975426e-16  1.576830e-15  3.459380e-16   
V12     0.124348  2.053457e-16 -9.568710e-17  6.310231e-16 -5.625518e-16   
V13    -0.065902 -2.425603e-17  6.295388e-16  2.807652e-16  1.303306e-16   
V14    -0.098757 -5.020280e-16 -1.730566e-16  4.739859e-16  2.282280e-16   
V15    -0.183453  3.547782e-16 -4.995814e-17  9.068793e-16  1.377649e-16   
V16     0.011903  7.212815e-17  1.177316e-17  8.299445e-16 -9.614528e-16   
V17    -0.073297 -3.879840e-16 -2.685296e-16  7.614712e-16 -2.699612e-16   
V18     0.090438  3.230206e-17  3.284605e-16  1.509897e-16 -5.103644e-16   
V19     0.028975  1.502024e-16 -7.118719e-18  3.463522e-16 -3.980557e-16   
V20    -0.050866  4.654551e-16  2.506675e-16 -9.316409e-16 -1.857247e-16   
V21     0.044736 -2.457409e-16 -8.480447e-17  5.706192e-17 -1.949553e-16   
V22     0.144059 -4.290944e-16  1.526333e-16 -1.133902e-15 -6.276051e-17   
V23     0.051142  6.168652e-16  1.634231e-16 -4.983035e-16  9.164206e-17   
V24    -0.016182 -4.425156e-17  1.247925e-17  2.686834e-19  1.584638e-16   
V25    -0.233083 -9.605737e-16 -4.478846e-16 -1.104734e-15  6.070716e-16   
V26    -0.041407 -1.581290e-17  2.057310e-16 -1.238062e-16 -4.247268e-16   
V27    -0.005135  1.198124e-16 -4.966953e-16  1.045747e-15  3.977061e-17   
V28    -0.009413  2.083082e-15 -5.093836e-16  9.775546e-16 -2.761403e-18   
Amount -0.010596 -2.277087e-01 -5.314089e-01 -2.108805e-01  9.873167e-02   
Class  -0.012323 -1.013473e-01  9.128865e-02 -1.929608e-01  1.334475e-01   

                  V5            V6            V7            V8            V9  \
Time    1.730721e-01 -6.301647e-02  8.471437e-02 -3.694943e-02 -8.660434e-03   
V1      1.812612e-17 -6.506567e-16 -1.005191e-15 -2.433822e-16 -1.513678e-16   
V2      5.157519e-16  2.787346e-16  2.055934e-16 -5.377041e-17  1.978488e-17   
V3     -6.539009e-17  1.627627e-15  4.895305e-16 -1.268779e-15  5.568367e-16   
V4     -1.719944e-15 -7.491959e-16 -4.104503e-16  5.697192e-16  6.923247e-16   
V5      1.000000e+00  2.408382e-16  2.715541e-16  7.437229e-16  7.391702e-16   
V6      2.408382e-16  1.000000e+00  1.191668e-16 -1.104219e-16  4.131207e-16   
V7      2.715541e-16  1.191668e-16  1.000000e+00  3.344412e-16  1.122501e-15   
V8      7.437229e-16 -1.104219e-16  3.344412e-16  1.000000e+00  4.356078e-16   
V9      7.391702e-16  4.131207e-16  1.122501e-15  4.356078e-16  1.000000e+00   
V10    -5.202306e-16  5.932243e-17 -7.492834e-17 -2.801370e-16 -4.642274e-16   
V11     7.203963e-16  1.980503e-15  1.425248e-16  2.487043e-16  1.354680e-16   
V12     7.412552e-16  2.375468e-16 -3.536655e-18  1.839891e-16 -1.079314e-15   
V13     5.886991e-16 -1.211182e-16  1.266462e-17 -2.921856e-16  2.251072e-15   
V14     6.565143e-16  2.621312e-16  2.607772e-16 -8.599156e-16  3.784757e-15   
V15    -8.720275e-16 -1.531188e-15 -1.690540e-16  4.127777e-16 -1.051167e-15   
V16     2.246261e-15  2.623672e-18  5.869302e-17 -5.254741e-16 -1.214086e-15   
V17     1.281914e-16  2.015618e-16  2.177192e-16 -2.269549e-16  1.113695e-15   
V18     5.308590e-16  1.223814e-16  7.604126e-17 -3.667974e

In [ ]:
cor = df.corr()

cor['Class']

Time     -0.012323
V1       -0.101347
V2        0.091289
V3       -0.192961
V4        0.133447
V5       -0.094974
V6       -0.043643
V7       -0.187257
V8        0.019875
V9       -0.097733
V10      -0.216883
V11       0.154876
V12      -0.260593
V13      -0.004570
V14      -0.302544
V15      -0.004223
V16      -0.196539
V17      -0.326481
V18      -0.111485
V19       0.034783
V20       0.020090
V21       0.040413
V22       0.000805
V23      -0.002685
V24      -0.007221
V25       0.003308
V26       0.004455
V27       0.017580
V28       0.009536
Amount    0.005632
Class     1.000000
Name: Class, dtype: float64

In [ ]:
cor_1 = cor[abs(cor['Class'])>0.05]

cor_2 = cor[abs(cor['Class'])>0.1]

In [ ]:
cor_1

Time            V1            V2            V3            V4  \
V1     0.117396  1.000000e+00  4.135835e-16 -1.227819e-15 -9.215150e-16   
V2    -0.010593  4.135835e-16  1.000000e+00  3.243764e-16 -1.121065e-15   
V3    -0.419618 -1.227819e-15  3.243764e-16  1.000000e+00  4.711293e-16   
V4    -0.105260 -9.215150e-16 -1.121065e-15  4.711293e-16  1.000000e+00   
V5     0.173072  1.812612e-17  5.157519e-16 -6.539009e-17 -1.719944e-15   
V7     0.084714 -1.005191e-15  2.055934e-16  4.895305e-16 -4.104503e-16   
V9    -0.008660 -1.513678e-16  1.978488e-17  5.568367e-16  6.923247e-16   
V10    0.030617  7.388135e-17 -3.991394e-16  1.156587e-15  2.232685e-16   
V11   -0.247689  2.125498e-16  1.975426e-16  1.576830e-15  3.459380e-16   
V12    0.124348  2.053457e-16 -9.568710e-17  6.310231e-16 -5.625518e-16   
V14   -0.098757 -5.020280e-16 -1.730566e-16  4.739859e-16  2.282280e-16   
V16    0.011903  7.212815e-17  1.177316e-17  8.299445e-16 -9.614528e-16   
V17   -0.073297 -3.879840e-16 -2.685296e-16  7.614712e-16 -2.699612e-16   
V18    0.090438  3.230206e-17  3.284605e-16  1.509897e-16 -5.103644e-16   
Class -0.012323 -1.013473e-01  9.128865e-02 -1.929608e-01  1.334475e-01   

                 V5            V6            V7            V8            V9  \
V1     1.812612e-17 -6.506567e-16 -1.005191e-15 -2.433822e-16 -1.513678e-16   
V2     5.157519e-16  2.787346e-16  2.055934e-16 -5.377041e-17  1.978488e-17   
V3    -6.539009e-17  1.627627e-15  4.895305e-16 -1.268779e-15  5.568367e-16   
V4    -1.719944e-15 -7.491959e-16 -4.104503e-16  5.697192e-16  6.923247e-16   
V5     1.000000e+00  2.408382e-16  2.715541e-16  7.437229e-16  7.391702e-16   
V7     2.715541e-16  1.191668e-16  1.000000e+00  3.344412e-16  1.122501e-15   
V9     7.391702e-16  4.131207e-16  1.122501e-15  4.356078e-16  1.000000e+00   
V10   -5.202306e-16  5.932243e-17 -7.492834e-17 -2.801370e-16 -4.642274e-16   
V11    7.203963e-16  1.980503e-15  1.425248e-16  2.487043e-16  1.354680e-16   
V12    7.412552e-16  2.375468e-16 -3.536655e-18  1.839891e-16 -1.079314e-15   
V14    6.565143e-16  2.621312e-16  2.607772e-16 -8.599156e-16  3.784757e-15   
V16    2.246261e-15  2.623672e-18  5.869302e-17 -5.254741e-16 -1.214086e-15   
V17    1.281914e-16  2.015618e-16  2.177192e-16 -2.269549e-16  1.113695e-15   
V18    5.308590e-16  1.223814e-16  7.604126e-17 -3.667974e-16  4.993240e-16   
Class -9.497430e-02 -4.364316e-02 -1.872566e-01  1.987512e-02 -9.773269e-02   

       ...           V21           V22           V23           V24  \
V1     ... -2.457409e-16 -4.290944e-16  6.168652e-16 -4.425156e-17   
V2     ... -8.480447e-17  1.526333e-16  1.634231e-16  1.247925e-17   
V3     ...  5.706192e-17 -1.133902e-15 -4.983035e-16  2.686834e-19   
V4     ... -1.949553e-16 -6.276051e-17  9.164206e-17  1.584638e-16   
V5     ... -3.920976e-16  1.253751e-16 -8.428683e-18 -1.149255e-15   
V7     ... -2.027779e-16 -8.898922e-16 -4.387401e-16  7.434913e-18   
V9     ...  1.936953e-16 -7.071869e-16 -5.214137e-16 -1.430343e-16   
V10    ...  1.177547e-15 -6.418202e-16  3.214491e-16 -1.355885e-16   
V11    ... -5.658364e-16  7.772895e-16 -4.505332e-16  1.933267e-15   
V12    ...  7.300527e-16  1.644699e-16  1.800885e-16  4.436512e-16   
V14    ... -3.356561e-16  3.740383e-16  3.883204e-16  2.003482e-16   
V16    ... -4.715090e-16 -7.923387e-17  5.020770e-16 -3.005985e-16   
V17    ... -8.230527e-16 -8.743398e-16  3.706214e-16 -2.403828e-16   
V18    ... -9.408680e-16 -4.819365e-16 -1.912006e-16 -8.986916e-17   
Class  ...  4.041338e-02  8.053175e-04 -2.685156e-03 -7.220907e-03   

                V25           V26           V27           V28    Amount  \
V1    -9.605737e-16 -1.581290e-17  1.198124e-16  2.083082e-15 -0.227709   
V2    -4.478846e-16  2.057310e-16 -4.966953e-16 -5.093836e-16 -0.531409   
V3    -1.104734e-15 -1.238062e-16  1.045747e-15  9.775546e-16 -0.210880   
V4     6.070716e-16 -4.247268e-16  3.977061e-17 -2.761403e-18  0.098732   
V5     4.808532e-16  4.319541e-16  6.590482e-16 -

In [ ]:
cor_2

Time            V1            V2            V3            V4  \
V1     0.117396  1.000000e+00  4.135835e-16 -1.227819e-15 -9.215150e-16   
V3    -0.419618 -1.227819e-15  3.243764e-16  1.000000e+00  4.711293e-16   
V4    -0.105260 -9.215150e-16 -1.121065e-15  4.711293e-16  1.000000e+00   
V7     0.084714 -1.005191e-15  2.055934e-16  4.895305e-16 -4.104503e-16   
V10    0.030617  7.388135e-17 -3.991394e-16  1.156587e-15  2.232685e-16   
V11   -0.247689  2.125498e-16  1.975426e-16  1.576830e-15  3.459380e-16   
V12    0.124348  2.053457e-16 -9.568710e-17  6.310231e-16 -5.625518e-16   
V14   -0.098757 -5.020280e-16 -1.730566e-16  4.739859e-16  2.282280e-16   
V16    0.011903  7.212815e-17  1.177316e-17  8.299445e-16 -9.614528e-16   
V17   -0.073297 -3.879840e-16 -2.685296e-16  7.614712e-16 -2.699612e-16   
V18    0.090438  3.230206e-17  3.284605e-16  1.509897e-16 -5.103644e-16   
Class -0.012323 -1.013473e-01  9.128865e-02 -1.929608e-01  1.334475e-01   

                 V5            V6            V7            V8            V9  \
V1     1.812612e-17 -6.506567e-16 -1.005191e-15 -2.433822e-16 -1.513678e-16   
V3    -6.539009e-17  1.627627e-15  4.895305e-16 -1.268779e-15  5.568367e-16   
V4    -1.719944e-15 -7.491959e-16 -4.104503e-16  5.697192e-16  6.923247e-16   
V7     2.715541e-16  1.191668e-16  1.000000e+00  3.344412e-16  1.122501e-15   
V10   -5.202306e-16  5.932243e-17 -7.492834e-17 -2.801370e-16 -4.642274e-16   
V11    7.203963e-16  1.980503e-15  1.425248e-16  2.487043e-16  1.354680e-16   
V12    7.412552e-16  2.375468e-16 -3.536655e-18  1.839891e-16 -1.079314e-15   
V14    6.565143e-16  2.621312e-16  2.607772e-16 -8.599156e-16  3.784757e-15   
V16    2.246261e-15  2.623672e-18  5.869302e-17 -5.254741e-16 -1.214086e-15   
V17    1.281914e-16  2.015618e-16  2.177192e-16 -2.269549e-16  1.113695e-15   
V18    5.308590e-16  1.223814e-16  7.604126e-17 -3.667974e-16  4.993240e-16   
Class -9.497430e-02 -4.364316e-02 -1.872566e-01  1.987512e-02 -9.773269e-02   

       ...           V21           V22           V23           V24  \
V1     ... -2.457409e-16 -4.290944e-16  6.168652e-16 -4.425156e-17   
V3     ...  5.706192e-17 -1.133902e-15 -4.983035e-16  2.686834e-19   
V4     ... -1.949553e-16 -6.276051e-17  9.164206e-17  1.584638e-16   
V7     ... -2.027779e-16 -8.898922e-16 -4.387401e-16  7.434913e-18   
V10    ...  1.177547e-15 -6.418202e-16  3.214491e-16 -1.355885e-16   
V11    ... -5.658364e-16  7.772895e-16 -4.505332e-16  1.933267e-15   
V12    ...  7.300527e-16  1.644699e-16  1.800885e-16  4.436512e-16   
V14    ... -3.356561e-16  3.740383e-16  3.883204e-16  2.003482e-16   
V16    ... -4.715090e-16 -7.923387e-17  5.020770e-16 -3.005985e-16   
V17    ... -8.230527e-16 -8.743398e-16  3.706214e-16 -2.403828e-16   
V18    ... -9.408680e-16 -4.819365e-16 -1.912006e-16 -8.986916e-17   
Class  ...  4.041338e-02  8.053175e-04 -2.685156e-03 -7.220907e-03   

                V25           V26           V27           V28    Amount  \
V1    -9.605737e-16 -1.581290e-17  1.198124e-16  2.083082e-15 -0.227709   
V3    -1.104734e-15 -1.238062e-16  1.045747e-15  9.775546e-16 -0.210880   
V4     6.070716e-16 -4.247268e-16  3.977061e-17 -2.761403e-18  0.098732   
V7    -3.094082e-16 -9.657637e-16 -1.782106e-15 -2.776530e-16  0.397311   
V10   -2.846052e-16 -3.028119e-16 -2.197977e-16  4.864782e-17 -0.101502   
V11   -5.600475e-16 -1.003221e-16 -2.640281e-16 -3.792314e-16  0.000104   
V12   -5.712973e-16 -2.359969e-16 -4.672391e-16  6.415167e-16 -0.009542   
V14   -8.547932e-16 -1.660327e-16  1.044274e-16  2.289427e-15  0.033751   
V16   -1.345418e-15 -7.290010e-16  6.789513e-16  7.588849e-16 -0.003910   
V17    2.666806e-16  6.932833e-16  6.148525e-16 -5.534540e-17  0.007309   
V18   -6.629212e-17  2.990167e-16  2.242791e-16  7.976796e-16  0.035650   
Class  3.307706e-03  4.455398e-03  1.757973e-02  9.536041e-03  0.005632   

          Class  
V1    -0.101347  
V3    -0.192961  
V4     0.133447  
V7    -0.187257  
V10   -0.216883  
V11    0.154

In [ ]:
ls_Feat1 = list(cor_1['Class'].index)

ls_Feat2 = list(cor_2['Class'].index)

print(ls_Feat1)
print(ls_Feat2)

print(len(ls_Feat1))
print(len(ls_Feat2))

['V1', 'V2', 'V3', 'V4', 'V5', 'V7', 'V9', 'V10', 'V11', 'V12', 'V14', 'V16', 'V17', 'V18', 'Class']
['V1', 'V3', 'V4', 'V7', 'V10', 'V11', 'V12', 'V14', 'V16', 'V17', 'V18', 'Class']
15
12


In [ ]:
df_1 = df[ls_Feat1]

df_2 = df[ls_Feat2]

print(df.shape)
print(df_1.shape)
print(df_2.shape)

(284807, 31)
(284807, 15)
(284807, 12)


In [ ]:
X1 = df_1.drop(columns='Class')
y1 = df_1['Class']

X2 = df_2.drop(columns='Class')
y2 = df_2['Class']

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 0.2, random_state = 42)

X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size = 0.2, random_state = 42)

In [ ]:
LR(X_train1, X_test1, y_train1, y_test1)

[[56854    10]
 [   40    58]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.85      0.59      0.70        98

    accuracy                           1.00     56962
   macro avg       0.93      0.80      0.85     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
LR(X_train2, X_test2, y_train2, y_test2)

[[56854    10]
 [   42    56]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.85      0.57      0.68        98

    accuracy                           1.00     56962
   macro avg       0.92      0.79      0.84     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
from sklearn.naive_bayes import GaussianNB

def GNB(X_train, X_test, y_train, y_test):
  Gaussian = GaussianNB()
  Gaussian.fit(X_train, y_train)

  y_pred = Gaussian.predict(X_test)
  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [ ]:
GNB(X_train, X_test, y_train, y_test)

[[56502   362]
 [   36    62]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56864
           1       0.15      0.63      0.24        98

    accuracy                           0.99     56962
   macro avg       0.57      0.81      0.62     56962
weighted avg       1.00      0.99      1.00     56962



In [ ]:
GNB(X_train1, X_test1, y_train1, y_test1)

[[56118   746]
 [   14    84]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     56864
           1       0.10      0.86      0.18        98

    accuracy                           0.99     56962
   macro avg       0.55      0.92      0.59     56962
weighted avg       1.00      0.99      0.99     56962



In [ ]:
GNB(X_train2, X_test2, y_train2, y_test2)

[[56262   602]
 [   14    84]]
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     56864
           1       0.12      0.86      0.21        98

    accuracy                           0.99     56962
   macro avg       0.56      0.92      0.60     56962
weighted avg       1.00      0.99      0.99     56962



In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

std = StandardScaler()
X_scl = std.fit_transform(X)

mm = MinMaxScaler()
X_mm = mm.fit_transform(X)

In [ ]:
X_train_scl, X_test_scl, y_train_scl, y_test_scl = train_test_split(X_scl, y, test_size = 0.2, random_state = 42)
X_train_mm, X_test_mm, y_train_mm, y_test_mm = train_test_split(X_mm, y, test_size = 0.2, random_state = 42)

In [ ]:
LR(X_train_scl, X_test_scl, y_train_scl, y_test_scl)

[[56855     9]
 [   41    57]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.86      0.58      0.70        98

    accuracy                           1.00     56962
   macro avg       0.93      0.79      0.85     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
LR(X_train_mm, X_test_mm, y_train_mm, y_test_mm)

[[56855     9]
 [   50    48]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.84      0.49      0.62        98

    accuracy                           1.00     56962
   macro avg       0.92      0.74      0.81     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
GNB(X_train_scl, X_test_scl, y_train_scl, y_test_scl)

[[55619  1245]
 [   18    80]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56864
           1       0.06      0.82      0.11        98

    accuracy                           0.98     56962
   macro avg       0.53      0.90      0.55     56962
weighted avg       1.00      0.98      0.99     56962



In [ ]:
GNB(X_train_mm, X_test_mm, y_train_mm, y_test_mm)

[[55619  1245]
 [   18    80]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56864
           1       0.06      0.82      0.11        98

    accuracy                           0.98     56962
   macro avg       0.53      0.90      0.55     56962
weighted avg       1.00      0.98      0.99     56962



In [ ]:
from sklearn import svm

def SVC(X_train, X_test, y_train, y_test):
  sc = svm.SVC()
  sc.fit(X_train, y_train)

  y_pred = sc.predict(X_test)
  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [ ]:
SVC(X_train, X_test, y_train, y_test)

[[56864     0]
 [   98     0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.00      0.00      0.00        98

    accuracy                           1.00     56962
   macro avg       0.50      0.50      0.50     56962
weighted avg       1.00      1.00      1.00     56962



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
 SVC(X_train_scl, X_test_scl, y_train_scl, y_test_scl)

[[56862     2]
 [   37    61]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.97      0.62      0.76        98

    accuracy                           1.00     56962
   macro avg       0.98      0.81      0.88     56962
weighted avg       1.00      1.00      1.00     56962

